language: node_js
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
addons:
  apt:
    packages:
      - xvfb
before_install:
  - export TZ=America/Los_Angeles
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
